ansible_become_pass: ENC[AES256_GCM,data:ApNpr88EtCdS,iv:ftxK90LP5N2fPxUo2oI4nWhcF203Vd9jOUVhkPFpIzs=,tag:DgpzW74xh9Gr8xwX8UdNUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0Nk55NEltTTV6VUhzMG0z
            QUsrRnlUT3IyL2dEblorbStPcE5tZnpRejJFCnZsSG54dnA0ZURLUGpDeHZxcFBF
            MnRXV1VYN2NpRXV1MG43SVljQlNWQncKLS0tIGRGNTI4Z1VuRjlZYkJMd1BKdWFL
            OFdsUlhmaTQ5bFVURkxyUnRheWx6S0kK+bf8PfANtshkWvUPFcSTUrQxWgTgvYuN
            q6k/zcqOLuf2s9XG6WPScqx9wQ5xyxiHJpG6h4D1qUPOsxsPtDvogA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-24T05:02:51Z"
    mac: ENC[AES256_GCM,data:DMhlXbqWDaxZClDGTwMLLLGNYKVTXbiWiJoGnFkSNvAbS6C45vVE55EAXEk+ZEpZ/kvJMG9KEFQpkwH9psBeIFg8HyU6pNjog91BtMb4L/KmJecglNHZ4YqFkxGoC7hoq1yP0IkZ/Q/P+T+98vtqoE4OFSzSADafYCzMtDwsd5I=,iv:J0an97bwDRia0V8luzD8AwR8czdXon1bHpTwvnKh+I8=,tag:0lzDuKPxzJKijjyQ6Xc+sQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.0
