apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-password: ENC[AES256_GCM,data:X0XPsZyXRHid,iv:McLHwmmn5OF7jY0626gSOdTavNklWbjhcfWcRFzru9k=,tag:nNK8fHwIR3rITWuvJGAP7w==,type:str]
    admin-user: ENC[AES256_GCM,data:w2zjhlQ=,iv:XCsATmtXcxHb5VSln3VxWcVxH/PjQU+OhPYDBDWAK+o=,tag:5eimuF5f93TYNv9BUwtODQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15l59vc6fnsh8uflxpn7damsjczq3gyaxcmqkj39q7lw2pah37ueq294saj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaXpJbDJBM3picmpCTHBK
            V2hOMHBhaWZPb2J6Y0lSR0VtaWt3cE9ZUkVNCmZGODZSN3ovY1RGUXZnbGwyVEFj
            L2dCTDVnTWNGcWRGWEwzUE81Ukt4Z1UKLS0tIENBdWlyQTcwMWJNcUtabE5rV1Y3
            UXdqK0xqSlREamRhR0wrNHEwZFIwUlEKmv2ze0AT9NvRZ8M0e9DyLbgUC50zarhv
            5n71WbyXp4rzCRFSB9OcgLAIhYL/IJglJymFb4uQXSs+zeLyVutBaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T21:34:22Z"
    mac: ENC[AES256_GCM,data:2HScj5MTNeee59skd38PzRkdTBZo58cV2gmoSnaGeodS9KUqsgPhI5aOM3FMwE780DSiF5rDhMgl4JU2rBs53Vw3DgNJl5wqalZ2hRV68mexmPsEMlxrCr3uE9zL7SjWTkhrlpOubWOLTQDAYXJjETrlPUoRLCfuzvJffFUdHs0=,iv:CQbE4PuWqina9VQtQnY47h6vrlZ0q3MaMupL0X974fg=,tag:bDCaBsxf9MwBAoLkECxXzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
