apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:eiypMfnwdsTtJ6w4x1y0vnXBdT7/Qtqm,iv:Xd9OjK2zx06oP23lfSMkkSVtSwGXHQwDmeEAYvOKg0s=,tag:Olsott58U+P+Sykx0MRydg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlSGExUzZrNVkyaEFLd09L
            Q2pjSmZLYklFdytiZExGQ3dTeFVPaWtZdm5BCkpLTkdMeWh4bHJZcmhTdFE3ZERp
            QlJjMFk5a1RNdFdEQ1NPREhXZEx4dm8KLS0tIGRZbWpDRWlpZG41TG9DK2pOOEwx
            UmlCUDh3Mmp5eEVnZlZ1MDNxTmd4TEEKyzAmKxvQsOv/z6Ff+pPITzsd5E4zrhQa
            25rdrdCrzxu+OG+8T3+p1sIYobDaZ9M8EsKkLU4qs/XPA9rxJaPezQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-24T05:03:30Z"
    mac: ENC[AES256_GCM,data:wp6/gSA/eYVqwuyLD36sTs6nibwmj9Q96LVfBteycXk/jCrsz3aOUfZZRsBOWBL3qPQ/0hA3NnaVNU8ejPDNZPdnnoUVn2HUxwjR3XF1fPu/GOwMxaRhG+whglvSTgyPDYfgqlDKcA687cOOampx7tR4+/VpsXph3abNAmO9gGM=,iv:4kjBbuo82gkTHQHHdu7Z+D/aM7rLijyNBKS9Us6RH/w=,tag:OyqDkhGrhVNv6dmx7+CsSg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
