---
kubernetes:
  children:
    master:
      hosts:
        blade1:
          ansible_user: dstewen
          ansible_host: 192.168.10.31
        blade2:
          ansible_user: dstewen
          ansible_host: 192.168.10.32
        blade3:
          ansible_user: dstewen
          ansible_host: 192.168.10.33
    worker:
      hosts:
        blade4:
          ansible_user: dstewen
          ansible_host: 192.168.10.34
        blade5:
          ansible_user: dstewen
          ansible_host: 192.168.10.35
        blade6:
          ansible_user: dstewen
          ansible_host: 192.168.10.36
        blade7:
          ansible_user: dstewen
          ansible_host: 192.168.10.37
        blade8:
          ansible_user: dstewen
          ansible_host: 192.168.10.38
