apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:e9TuuekIT2ELM8c7igJq5WZgbBPbmKvvWWtbGQ17sqwGaoR6HN4poQ==,iv:2AOnltu86hRXR/ImwjyVcA+GLZFDk0Z2fVHO0L/0W+A=,tag:Fm2x7+gjmRrU8bHxv5vF6w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4dHVHUUNKVHRPZnJRT1hI
            cG9RR3lyYTlaTW90cEJnYm1sRzZZYmVtMlNVClNaODl5WWhqUElGYTFTNk1vOEpW
            Sk83cWpoYWE2Q2xTa3k2MG1iVkNZQ0EKLS0tIFNDdERXVGNHZ09oTlBhUGx3bTJQ
            UFNnSkx5UXpQbitIY0dWTUpIc1QwYUUK5KVTmlHGdeX4Z56WgidmGM8dbFajvPTD
            JTMeqnMxqOyE+lWgVGKYSyalvmVjHSx2BbfYo1qLMArnNQ16y7X7cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-24T05:03:30Z"
    mac: ENC[AES256_GCM,data:uBXrpPoGrJV8rJ9puFNWXQEojT50s57obdTHZ5QbrTvIHywTFUNKTTwbLA0s2Tw46sADQ3u74eDOAYb5uXd858f/5zOG7GRHK8M4we/xs27EYGryJrJ83+kq3Di8HWlKo/JueUbz7//L7xoMNS8w8nyGcP4yXQkeGnK0cBjqS28=,iv:AAB6XObwkZq42zbm9vSrkVuUd5e+sKnRuQ4p08nJ0mw=,tag:XXi76Y3FTgherruK1EH0ww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
