apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:Sa2EljEWTjfSjSgzzzwSREGo14uy8fOP/iVJpKOVUaWfqYESiszMv2jg+WK4J5knRayib4mk39x+yuG1,iv:0NRns4j4FcrViHuaX6NU2k1kdLijzJ5kD3XOVclDcpM=,tag:9Mx6EWFpimU/7HING/7VDA==,type:str]
    username: ENC[AES256_GCM,data:wgkmLeI=,iv:jmBbM5X4CTA4vqCAw6A8iDUl2aNMprZ3TOQryXHL2qo=,tag:P7QoCwENUlLXjPaR3kJy9A==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age15l59vc6fnsh8uflxpn7damsjczq3gyaxcmqkj39q7lw2pah37ueq294saj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2c0tER2hBQ3NkelZHRHhJ
            MjJLUjJxZ2RrdjdmWjlScVNPY0p1QktMbFJnCllQeTZWWEUvR0h2Q2JldU9MaVRI
            b3ZIWWs0YnJ5akV4Z0QwR1pLaGJqcTQKLS0tIFNtZFhudEhuN0k3K1FqeDJuVzM4
            a1I2TXJtSkhsdlBrekI1YjNyTm9kWEkKoCT0yCBrjuqtHT5G8HWAsmMLgysLXlEe
            XFVe1nnT86w5TtT74TTSnucK8MjD+/gXCd1qaR9Cg6iUKy4OBWOS1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-23T23:33:14Z"
    mac: ENC[AES256_GCM,data:iiXKCCvDIaDxlh2t6yvJ//StT7CZYQqGjVUMHz9tYOc4eVtac7kFnV688oGaZLLbgQdQ8QaKKmBvKwRVbateQsSU0xM9UXAh+K9Rz8j4soSGfBjy9ZBo5I/MAF+WJ6PXUCHextiE1ZjM5wgpN3Maq1sF2Ud893Cfuv0autOdXSo=,iv:KGNjc/hOOaeVAz5RPfh/WX5W+ufFfV/wxpfggW7tgwQ=,tag:uAK5o2W4i9sPRw37iCoGzw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
