apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:YZBxQvF9GuvT8GX+Fxya+SkTKN/9,iv:k6tTK2DhLbRHL06GcbQXAzkkEZsQZoiidVhDo+QMPV4=,tag:OAtn0SvmdbM+jHbIDfDvBQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:rzV6/MmgkVLY1tu+iEvKXt0RB1U3CxIKW7hUdhAZ0f3P/jv+,iv:Slc22gv73Dt8XZjozpoj09RoTG4+mtIhMUHPnsFGegw=,tag:nyppFZ6IybM+PXtMtJmdZg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:yrxhAR7ojVx3OqWy38rD,iv:m1ikk0OClkFKJkx2q+qgRCnu3m5NHbq5AhlICc5HxbY=,tag:Csh1jxCTK739xaurJHUYtw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzU3FiMzJ4Y3Q5Kzh3NUt6
            NW54RHh6bUpHWVFuT1JhOGxZemtrcHlDYlIwCjZ1Z2huUS9nbzFlaDQ1VzJDeEsy
            VXJDZWp3TFI1cVB3QjFhSXNDdGdNbWcKLS0tIDhPemdSK1AzN2JuQ2EvU1FvdGhX
            SU12ZHFOa0hreWJGSkUrOE1TanIzVkEKo4gNqPFX8dBtCYMrPzH76pmmUMQu8t/v
            8Ws+odJGtlmdPCpx3Bw6Hz20St+pFMatc560jZP/HCV9mtl+vg/p4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-24T05:03:30Z"
    mac: ENC[AES256_GCM,data:bSeayTWXeXMKhfEFYuqwohrBXGg9hDvFXNXjLCUO2n9doISxS5O0YRJBxm6Psz7Xf0qc3dBH3opijh+bjvYaNJ0Wg5WVZXMbWeQDU1U+kqn923Kf+wdmFr10cfLkg6GFwWirEm41cY9llXW5pMVPlgYty3Pn36UsGgn7Gcqg1xw=,iv:G+j47ZNkzVf/FN0+CFKy9h3p4yGkpUDOOorn+t4KCd0=,tag:O7Gq3UUYk+UKLYT9mNC7cQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.0
